version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - flask-mongo-net

  flask:
    image: ilefrjiba/flask-app
    container_name: flask
    ports:
      - "5000:5000"
    networks:
      - flask-mongo-net
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    
networks:
  flask-mongo-net: