deployments:
  - name: webdb
    label: webdb
    image: ilefrjiba/flask-app:v2
    replicas: 3
    port: 5000
    matchLabels: webdb
    env:
      MONGO_URL: mongodb-service.irjiba.svc.cluster.local:27017

  - name: webnodb
    label: webnodb
    image: ilefrjiba/flask-app:v1
    replicas: 2
    port: 5000
    matchLabels: webnodb

services:
  - name: webnodb-service
    app: webnodb
    port: 80
    targetPort: 5000

  - name: webdb-service
    app: webdb
    port: 8080
    targetPort: 5000



ingress:
  name: ingress
  rules:
    - host: webnodb.irjiba.net4255.luxbulb.org
      serviceName: webnodb-service
      servicePort: 80
    - host: webdb.irjiba.net4255.luxbulb.org
      serviceName: webdb-service
      servicePort: 8080
      
mongo_statefulset:
  name: mongostatefulset
  label: mongodb
  image: mongo
  replicas: 1
  port: 27017
  matchLabels: mongodb
  volumeMounts:
    name: mongodb-data
    path: /data/db

mongo_pvc:
  name: mongodb-data
  accessModes: [ "ReadWriteOnce" ]
  storage: 0.4Gi

mongo_headless:
  name: mongodb-service
  app: mongodb
  port: 27017
  targetPort: 27017