apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod
  namespace: irjiba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
      - name: test-container
        image: alpine
        command: ["/bin/sh", "-c", "sleep 3600"]
        tty: true