{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: irjiba
  labels:
    app: {{ .label }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .matchLabels }}
  template:
    metadata:
      labels:
        app: {{ .matchLabels }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: {{ .port }}
        {{- if .env }}
        env:
        {{- range $key, $value := .env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
{{- end }}
