{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: irjiba
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
  - protocol: TCP
    port: {{ .port }}
    targetPort: {{ .targetPort }}                       
---
{{- end }}
